optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 300
  batch_size: 4096
  save_model: false
  loss: pairwise_with_epoch_flag
  log_loss: false
  test_step: 3
  patience: 5
  reproducible: true
  seed: 2023

test:
  metrics: [recall, ndcg]
  k: [10, 20, 40]
  batch_size: 1024

data:
  type: general_cf
  name: yelp

model:
  name: ncl
  keep_rate: 1.0
  layer_num: 3
  high_order: 2
  reg_weight: 1.0e-7
  proto_weight: 1.0e-4
  struct_weight: 1.0e-3
  temperature: 0.1
  embedding_size: 32
  epoch_period: 3
  cluster_num: 50

tune:
  enable: true
  hyperparameters: [temperature, proto_weight, struct_weight]
  temperature: [0.1, 0.2, 0.3, 0.5, 1.0]
  proto_weight: [1.0e-2, 1.0e-3, 1.0e-4]
  struct_weight: [1.0e-1, 1.0e-2, 1.0e-3]