optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 300
  batch_size: 4096
  save_model: false
  loss: pairwise
  log_loss: false
  test_step: 3
  patience: 5
  reproducible: true
  seed: 2023

test:
  metrics: [recall, ndcg]
  k: [10, 20, 40]
  batch_size: 1024

data:
  type: general_cf
  name: lastfm

# 模型参数
# model:
#   name: nsgcl
#   layer_num: 3
#   denoise_num: 5
#   vgae_num: 4
#   reg_weight: 1.0e-8
#   alpha: 5.0e-3
#   beta: 0.1
#   gamma: 1.0e-2
#   temperature: 0.1
#   keep_rate: 0.5
#   embedding_size: 32

# 数据集 lastfm
model:
  name: nsgcl
  layer_num: 2
  denoise_num: 2
  vgae_num: 4
  reg_weight: 1.0e-8
  alpha: 0.005
  beta: 0.005
  temperature: 0.2
  keep_rate: 0.5
  embedding_size: 32

# 数据集 3


# 网格搜索
tune:
  enable: true
  hyperparameters: [layer_num, denoise_num, vgae_num, reg_weight, alpha, beta, temperature]
  layer_num: [2, 3, 4]
  denoise_num: [2]
  vgae_num: [4]
  reg_weight: [1.0e-4, 1.0e-3]
  alpha: [1.0e-3, 2.0e-3, 5.0e-3, 1.0e-2, 2.0e-2]
  beta: [1.0e-3, 2.0e-3, 5.0e-3, 1.0e-2, 2.0e-2]
  temperature: [0.2]